#' Test nucleotide substitution models (PartitionFinder)
#'
#' Create a configuration file and bash script for determining the best-fit
#' partitioning scheme and nucleotide substitution model(s) for a multiple
#' sequence alignment (either single-marker or concatenated) using
#' PartitionFinder.
#'
#' @param aln_file Name of the file containing the PHYLIP multiple sequence
#'   alignment (either single-marker or concatenated) to be analysed by
#'   PartitionFinder (default "aln.phy").
#' @param cpart Is the alignment to be partitioned by codon position?
#' @param cpos_obj A (flattened) list of vectors describing the positions of
#'   codons 1, 2 and 3 in the alignment, as generated by `get_cmasks()` (for
#'   single-marker alignments) or `concat_alns()` (for concatenated alignments).
#' @param marker For a single-marker analysis, the name of the genetic marker;
#'   or, for a concatenated analysis, "conc".
#' @param conc_pos_obj For concatenated sequences, a list of vectors describing
#'   the start and end positions of each constituent single-marker alignment, as
#'   generated by `concat_alns()`.
#' @param aln_obj A `phangorn` phyDat object containing the multiple sequence
#'   alignment.
#' @param pf_dir Path to the target directory for the PartitionFinder analysis,
#'   which should contain the multiple sequence alignment as a PHYLIP file.
#' @param bscr_dir Path to the directory in which the PartitionFinder bash
#'   script will be created.
#' @param run If TRUE, the bash script is run in Windows Subsystem for Linux
#'   (WSL) as a native R process.
#' @return No objects are returned. A configuration file named
#'   `partition_finder.cfg` and a bash script named `partitionfinder.sh` are
#'   created in the specified PartitionFinder and script directories,
#'   respectively. If run, the bash script generates results in a sub-directory
#'   `./analysis` within the PartitionFinder directory.
#' @examples
#' testmods_pf()
#' @export
testmods_pf <- function (
  aln_file = "aln.phy", cpart = FALSE, cpos_obj = NULL,
  marker, conc_pos_obj = NULL, aln_obj, pf_dir, bscr_dir, run = FALSE
) {
  # create the PartitionFinder configuration file:
  readr::write_lines(  # output the following lines...
    c(
      paste0("alignment = ",aln_file,";"),  # alignment file name
      "branchlengths = unlinked;",
      "models = all;",
      "model_selection = aicc;",
      "[data_blocks]",  # start data blocks definition section

      # lines specifying data blocks:
      if (cpart) {  # if partitioning by codon (including concatenated aln.s),
        purrr::map2(cpos_obj, names(cpos_obj), ~ {  # for each block,
          # codon positions as a string of multiple sites separated by spaces:
          paste0(.y," = ",paste(.x, collapse = " "),";")
        })
      } else if (marker == "conc") {  # otherwise, for concatenated alignments,
        purrr::map2(conc_pos_obj, names(conc_pos_obj), ~ {
          # for each single-marker alignment, a single start and end position:
          paste0(.y," = ",paste(.x, collapse = " "),";")
        })
      } else {  # otherwise (i.e. for single, unpartitioned marker),
        paste0(marker," = 1-",ncol(phangorn::phyDat2MultipleAlignment(aln_obj)),";")
      },

      # remaining lines:
      "[schemes]",  # partitioning scheme section
      "search = greedy;"
    ),
    # ...to the following file:
    paste0(pf_dir,"partition_finder.cfg")
  )

  # create bash script for running PartitionFinder:
  readr::write_lines(  # output the following lines...
    c(
      "#!/bin/bash",  # bash script header
      "# Selecting best-fit partitioning scheme and substitution models (PartitionFinder)",
      paste0('cd "',pf_dir,'"'),  # change directory
      "rm -R analysis/",  # remove results of previous analysis
      "rm log.txt",  # remove log file (otherwise current log is just appended)
      paste0(  # run PartitionFinder analysis
        "python ~/partitionfinder-2.1.1/PartitionFinder.py ./ ")
      # "--no-ml-tree")  # (NB -- only if cannot remove unused sites from alignment;
      # but this uses Maximum Parsimony, rather than Maximum Likelihood)
    ),
    # ...to the following file:
    paste0(bscr_dir,"partitionfinder.sh")
  )

  if (run) {  # if specified, run the script via WSL:
    system(paste0('bash -c "',bscr_dir,'partitionfinder.sh"'))
  }
}
